[package]
name = "jito-protos"
version = "0.1.1"
edition = "2021"
publish = false

[dependencies]
bincode = "1"
# bytes = "1"
prost = "0.12"
prost-types = "0.12"
solana-perf = "2"
solana-sdk = "2"
tonic = "0.10"

[build-dependencies]
tonic-build = "0.10"
